# Generated by Django 2.1 on 2022-10-13 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20221010_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ('-created_at',), 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
    ]
